name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the artifact
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls -latr
      - name: Output info
        run: echo "Deploying and reuse..."
